#!/usr/bin/env php
<?php

require $_composer_autoload_path ?? __DIR__.'/vendor/autoload.php';

$workingPath = is_string(getenv('TESTBENCH_WORKING_PATH'))
    ? getenv('TESTBENCH_WORKING_PATH')
    : getcwd();

define('TESTBENCH_CORE', true);
define('TESTBENCH_DUSK', true);
define('TESTBENCH_WORKING_PATH', $workingPath);

$config = Orchestra\Testbench\Foundation\Config::loadFromYaml(
    workingPath: $workingPath,
    defaults: [
        'providers' => ['Laravel\Dusk\DuskServiceProvider'],
        'dont-discover' => [],
    ],
);

$commander = new Orchestra\Testbench\Dusk\Console\Commander($config->getAttributes(), $workingPath);

$commander->handle();
