#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    // Development environment.
    require __DIR__.'/vendor/autoload.php';
} else {
    // Installation environment.
    require __DIR__.'/../../autoload.php';
}

$workingPath = is_string(getenv('TESTBENCH_WORKING_PATH'))
    ? getenv('TESTBENCH_WORKING_PATH')
    : getcwd();

define('TESTBENCH_CORE', true);
define('TESTBENCH_DUSK', true);
define('TESTBENCH_WORKING_PATH', $workingPath);

$config = ['env' => [], 'providers' => ['Laravel\Dusk\DuskServiceProvider']];

if (file_exists("{$workingPath}/testbench.yaml")) {
    $config = Symfony\Component\Yaml\Yaml::parseFile("{$workingPath}/testbench.yaml");
}

$commander = new Orchestra\Testbench\Dusk\Console\Commander($config, $workingPath);

$commander->handle();
